{% set name = "pyreadline3" %}
{% set version = "3.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 61e53218b99656091ddb077df9e71f25850e72e030b6183b39c9b7e6e4f4a9bf

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [not win]
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools-scm
    - setuptools-git-versioning
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - pyreadline3
    - pyreadline3.clipboard
    - pyreadline3.configuration
    - pyreadline3.console
    - pyreadline3.keysyms
    - pyreadline3.lineeditor
    - pyreadline3.modes
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -ra -v --tb=short tests

about:
  home: https://github.com/pyreadline3/pyreadline3
  summary: A python implementation of GNU readline
  description: Python implementation of GNU readline functionality
  license: BSD-3-Clause
  license_family: BSD
  license_file: doc/COPYING
  dev_url: https://github.com/pyreadline3/pyreadline3
  doc_url: https://github.com/pyreadline3/pyreadline3

extra:
  recipe-maintainers:
    - tschoonj
